version: "3.7"
services:
  spring_boot:
    build: .
    restart: always
    ports:
      - 9090:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/melifera?allowPublicKeyRetrieval=true
      - EMAIL_USERNAME=vehicleproject528@gmail.com
      - EMAIL_PASSWORD=hjhwmwyuzdldpoke
      - CONFIRMATION.URL=http://localhost:9090
      - HELLO_MESSAGE=Testingg
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: melifera
      DATABASE_USERNAME: root
      MYSQL_ROOT_PASSWORD: 12345678

networks:
  springapimysql-net:
